sources:
  - name: Mongoose
    handler:
      mongoose:
        connectionString: mongodb://root:example@localhost:8081/test
        models:
          - name: User
            path: ./src/models.js#User

documents:
  - ./example-queries/*.graphql
