export default {
  'extending-unified-schema': 'Extending the Unified Schema',
  batching: 'Batching for N+1 Problem',
  'error-masking': 'Error Masking',
  'monitoring-and-tracing': 'Monitoring and Tracing',
  auth0: 'Authentication with Auth0',
  'subscriptions-webhooks': 'Subscriptions & Webhooks',
  'file-uploads': 'File Uploads',
  hive: 'Integration with Hive',
  'graphql-code-generator': 'Configure GraphQL Code Generator',
  'mesh-sdk': 'Programmatic Usage / SDK',
  sofa: 'Generate REST API with SOFA',
  headers: 'Headers',
  'dynamic-vars': 'Dynamic Variables',
  'persisted-operations': 'Persisted Operations',
};
