sources:
  - name: Hello World
    handler:
      jsonSchema:
        operations:
          - type: Query
            field: greeting
            method: GET
            path: /
            responseSample: greeting.json
transforms:
  - mock:
      mocks:
        - apply: Query.greeting
documents:
  - |
    query HelloWorld {
      greeting
    }
