checksumBehavior: ignore

nodeLinker: node-modules

npmAuthToken: '${NPM_TOKEN:-}'

npmPublishProvenance: true

npmPublishRegistry: 'https://registry.npmjs.org/'

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
