sources:
  - name: Weatherbit
    handler:
      newOpenapi:
        baseUrl: http://api.weatherbit.io/v2.0/
        oasFilePath: https://www.weatherbit.io/static/swagger.json

plugins:
  - responseCache:
      ttlPerCoordinate:
        # Forcast data might change, so we can cache it for 1 hour only
        - coordinate: Query.forecast_daily_by_lat_by_lon
          ttl: 864000

documents:
  - ./*.graphql
