sources:
  - name: Weatherbit
    handler:
      openapi:
        source: https://www.weatherbit.io/static/swagger.json

plugins:
  - responseCache:
      ttlPerCoordinate:
        # Forecast data might change, so we can cache it for 1 hour only
        - coordinate: Query.forecast_daily_by_lat_by_lon
          ttl: 3600

documents:
  - ./*.graphql
