sources:
  - name: Example
    handler:
      jsonSchema:
        baseUrl: http://localhost:4002
        operationHeaders:
          Content-Type: application/json
        operations:
          - type: Query
            field: todos
            path: /todos
            method: GET
            responseSample: ./todos.json
          - type: Mutation
            field: addTodo
            path: /todo
            method: POST
            requestSample: ./addTodo.json
            responseSample: ./todo.json
          - type: Subscription
            field: todoAdded
            pubsubTopic: todoAdded
            responseSample: ./todo.json

serve:
  port: 4000
  handlers:
    - path: /webhooks/todo_added
      method: POST
      pubsubTopic: todoAdded

documents:
  - ./example-queries/**/*.graphql

additionalTypeDefs: |
  directive @live on QUERY

plugins:
  - liveQuery:
      liveQueryInvalidations:
        - field: Mutation.addTodo
          invalidate:
            - Query.todos
