sources:
  - name: Example
    handler:
      grpc:
        endpoint: localhost:50051
        credentialsFunction: ./auth.js
        protoFilePath:
          file: io/xtech/service.proto
          load:
            includeDirs:
              - ./proto
        serviceName: Example
        packageName: io.xtech
