sources:
  - name: Example
    handler:
      grpc:
        endpoint: localhost:50051
        metaData:
          someKey: 'someValue'
          connection_type: ['headers', 'connection']
        protoFilePath:
          file: ./proto/service.proto
          load:
            includeDirs:
              - ./proto
    transforms:
      - namingConvention:
          fieldNames: camelCase

documents:
  - example-queries/*.graphql

skipSSLValidation: true
