sources:
  - name: Example
    handler:
      grpc:
        endpoint: localhost:50051
        protoFilePath: grpc/proto/Example.proto
        serviceName: Example
        packageName: io.xtech.example
