sources:
  - name: Hello World
    handler:
      jsonSchema:
        operations:
          - type: Query
            field: greeting
            method: GET
            responseTypeName: String
transforms:
  - mock:
      mocks:
        - apply: Query.greeting
serve:
  exampleQuery: |
    query HelloWorld {
      greeting
    }
