sources:
  - name: Hello World
    handler:
      jsonSchema:
        operations:
          - type: Query
            field: greeting
            method: GET
            path: /
            responseSample: greeting.json
plugins:
  - mock:
      mocks:
        - apply: Query.greeting
  # Example for creating a REST API
  - sofa:
      basePath: /rest
      swaggerUI:
        endpoint: /swagger
      openAPI:
        info:
          title: 'My REST API'
          version: '1.0.0'
documents:
  - |
    query HelloWorld {
      greeting
    }
