sources:
  - name: YouTrack
    handler:
      openapi:
        source: ${YOUTRACK_SERVICE_URL}/api/openapi.json
        baseUrl: ${YOUTRACK_SERVICE_URL}/api/
        schemaHeaders:
          Authorization: Bearer ${YOUTRACK_TOKEN}
        operationHeaders:
          Authorization: Bearer ${YOUTRACK_TOKEN}
    transforms:
      # Each YouTrack needs `fields` query parameter
      # So thanks to GraphQL, we know which fields client needs
      # And we can prevent overfetching in this way
      - resolversComposition:
          mode: bare
          compositions:
            - resolver: Query.*
              composer: ./src/add-fields

documents:
  - get-projects-with-issues.graphql
