sources:
  - name: Wiki
    handler:
      openapi:
        source: https://wikimedia.org/api/rest_v1/?spec
        endpoint: https://wikimedia.org/api/rest_v1

additionalTypeDefs: |
  extend type Query {
    viewsInPastMonth(project: String!): BigInt!
  }
additionalResolvers:
  - ./additional-resolvers.ts

documents:
  - example-queries/*.graphql
