sources:
  - name: Wiki
    handler:
      openapi:
        source: https://api.apis.guru/v2/specs/wikimedia.org/1.0.0/swagger.yaml
        operationIdFieldNames: true

additionalTypeDefs: |
  extend type Query {
    viewsInPastMonth(project: String!): Float!
  }
additionalResolvers:
  - ./additional-resolvers.ts

documents:
  - example-queries/*.graphql
