sources:
  - name: Microsoft Graph
    handler:
      odata:
        endpoint: https://graph.microsoft.com/v1.0/
        batch: json
        operationHeaders:
          Authorization: Bearer {context.accessToken}

documents:
  - './documents/*.graphql'
