sources:
  - name: FHIR
    handler:
      fhir:
        endpoint: http://hapi.fhir.org/baseR4

  - name: Covid
    handler:
      graphql:
        endpoint: https://covid-19-two-rust.vercel.app/api/graphql
additionalTypeDefs: |
  extend type Address {
    case: Case
  }
additionalResolvers:
  - type: Address # Declarative API
    field: case
    requiredSelectionSet: |
      {
        country
      }
    targetSource: Covid
    targetMethod: case
    args:
      countryRegion: '{root.country}'

serve:
  exampleQuery: ./example-queries/*.graphql
