sources:
  - name: UploadFiles
    handler:
      graphql:
        endpoint: http://localhost:3001/graphql
        multipart: true
  - name: ResizeImages
    handler:
      graphql:
        endpoint: http://localhost:3002/graphql

additionalTypeDefs: |
  extend type File {
    thumbnailImage(width: Int, height: Int): String
  }
additionalResolvers:
  - targetTypeName: File
    targetFieldName: thumbnailImage
    requiredSelectionSet: '{ base64 }'
    sourceName: ResizeImages
    sourceFieldName: resizeImage
    sourceArgs:
      image: '{root.base64}'
      width: '{args.width}'
      height: '{args.height}'

serve:
  cors:
    origin: '*'
  maxRequestBodySize: 10mb
