export default {
  'handlers-introduction': 'Introduction',
  graphql: 'GraphQL',
  openapi: 'OpenAPI / Swagger',
  supergraph: 'Federation Supergraph',
  grpc: 'gRPC / Protobuf',
  'json-schema': 'JSON Schema or Samples',
  postgraphile: 'PostgreSQL / PostGraphile',
  soap: 'SOAP',
  mongoose: 'MongoDB / Mongoose',
  odata: 'OData / Microsoft Graph',
  thrift: 'Apache Thrift',
  tuql: 'SQLite / Tuql',
  mysql: 'MySQL',
  neo4j: 'Neo4j',
};
