sources:
  - name: OpenAPICallbackExample
    handler:
      openapi:
        source: ./openapi.yml
        endpoint: http://localhost:4001

documents:
  - ./example-queries/**/*.graphql

serve:
  port: 4000
