sources:
  - name: accounts
    handler:
      graphql:
        endpoint: http://localhost:9871/graphql
    transforms:
      - federation:
          types:
            - name: User
              config:
                key:
                  - fields: id
                resolveReference:
                  queryFieldName: user
                  args:
                    id: '{root.id}'
  - name: reviews
    handler:
      graphql:
        endpoint: http://localhost:9872/graphql
  - name: products
    handler:
      graphql:
        endpoint: http://localhost:9873/graphql
  - name: inventory
    handler:
      graphql:
        endpoint: http://localhost:9874/graphql

documents:
  - example-query.graphql

serve:
  playground: true
