sources:
  - name: Geo
    handler:
      postgraphile:
        connectionString: postgres://postgres:docker@localhost:5432/postgres
    transforms:
      - prefix:
          value: Geo
  - name: Github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        schemaHeaders:
          Authorization: bearer ${GH_ACCESS_TOKEN}
        operationHeaders:
          Authorization: bearer ${GH_ACCESS_TOKEN}
    transforms:
      - prefix:
          value: Github
          includeRootOperations: true

additionalTypeDefs: |
      extend type GeoCity {
        developers(limit: Int = 10): GithubUserConnection
      }

require:
  - "ts-node/register/transpile-only"
additionalResolvers:
  - ./src/additionalResolvers.ts

documents: 
  - ./src/test.query.graphql
