sources:
  - name: Geo
    handler:
      postgraphile:
        connectionString: postgres://postgres:docker@localhost:5432/postgres
        cacheIntrospection: 
          ttl: 3600
    transforms:
      - prefix:
          value: Geo
  - name: Github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        introspection: https://raw.githubusercontent.com/octokit/graphql-schema/master/schema.graphql
        operationHeaders:
          Authorization: bearer ${GH_ACCESS_TOKEN}
        cacheIntrospection: 
          ttl: 3600
    transforms:
      - prefix:
          value: Github
          includeRootOperations: true

additionalTypeDefs: |
      extend type GeoCity {
        developers(limit: Int = 10): [GithubUser]
      }
additionalResolvers:
  - type: GeoCity
    field: developers
    requiredSelectionSet: |
      {
        name
      }
    targetSource: Github
    targetMethod: Githubsearch
    returnData: nodes
    args:
      type: "USER"
      query: "location:{root.name}"
      first: "{args.limit}"

cache:
  file:
    path: ./mesh-cache.json

serve:
  exampleQuery: ./src/test.query.graphql