sources:
  - name: Geo
    handler:
      postgraphile:
        connectionString: postgres://postgres:docker@localhost/postgres
    transforms:
      - prefix:
          value: Geo_
  - name: Github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        headers:
          Authorization: bearer ${GH_ACCESS_TOKEN}
    transforms:
      - prefix:
          value: Github_
          includeRootOperations: true
transforms:
  - extend: |
      extend type GeoCity {
        developers(limit: Int = 10): GithubSearchResultItemConnection!
      }
require:
  - ts-node/register/transpile-only
additionalResolvers:
  - ./src/mesh/additional-resolvers.ts
