sources:
  - name: PetStore
    handler:
      openapi:
        endpoint: https://petstore.swagger.io/v2/
        source: https://petstore.swagger.io/v2/swagger.json

documents:
  - './list-pets.graphql'
