merger: bare
sources:
  - name: Swapi
    handler:
      openapi:
        source: ./swagger/pets.json
        endpoint: >-
          http://localhost:4001
    transforms:
        - namingConvention:
            mode: bare
            typeNames: pascalCase
            enumValues: upperCase
            fieldNames: camelCase
            fieldArgumentNames: camelCase
