merger: bare
sources:
  - name: Search_V1
    handler:
      openapi:
        source: ./swagger/pets.json
        endpoint: >-
          http://localhost:4001
additionalResolvers:
  - ./src/extensions/resolvers
additionalTypeDefs:
  - ./src/extensions/typeDefs.graphql
