export default {
  index: 'Introduction',
  graphql: 'GraphQL',
  openapi: 'OpenAPI',
  grpc: 'gRPC / Protobuf',
  'json-schema': 'JSON Schema',
  soap: 'SOAP',
  odata: 'OData',
  thrift: 'Thrift',
  sqlite: 'SQLite',
  mysql: 'MySQL',
  neo4j: 'Neo4j',
  postgres: 'PostgreSQL (soon)',
  mongodb: 'MongoDB (soon)',
};
