openapi: 3.1.0
info:
  title: Books Example
  version: 1.0.0
paths:
  /books:
    get:
      operationId: books
      description: Returns a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{id}:
    get:
      operationId: book
      description: Returns a single book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: The book was not found
  /books/authors/{authorId}:
    get:
      operationId: booksByAuthor
      description: Returns a list of books by author
      parameters:
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '404':
          description: The author was not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        authorId:
          type: string
