export default {
  index: 'Introduction',
  'getting-started': 'Getting Started',
  'source-handlers': 'Source Handlers',
  transforms: 'Transforms',
  'schema-extensions': 'Schema Extensions',
  'type-merging': 'Type Merging',
  'response-caching': 'Response Caching',
  'rate-limit': 'Rate Limit',
  auth: 'Authentication',
  'subscriptions-webhooks': 'Subscriptions & Webhooks',
  'consume-in-other-gateways': 'Consume in Other Gateways',
  'local-execution': 'Local Execution',
  'migration-from-v0': 'Migration from Mesh v0',
};
