sources:
  - name: CountryInfo
    handler:
      soap:
        wsdl: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL
    transforms:
      - snapshot:
          if: "process.env.NODE_ENV != 'production'"
          apply:
            - Query.*
            - Mutation.*
          outputDir: snapshots

documents:
  - list-of-languages-by-name.graphql
