export default {
  index: 'Overview',
  'error-masking': 'Error Masking',
  cors: 'CORS',
  'csrf-prevention': 'CSRF Prevention',
  'rate-limiting': 'Rate Limiting',
  'disable-introspection': 'Introspection',
  https: 'HTTPS',
  'hmac-signature': 'HMAC Signature',
  'audit-documents': 'Audit Documents',
  'block-field-suggestions': 'Block Field Suggestions',
  'character-limit': 'Character Limit',
  'cost-limit': 'Cost Limit',
  'max-aliases': 'Max Aliases',
  'max-depth': 'Max Depth',
  'max-directives': 'Max Directives',
  'max-tokens': 'Max Tokens',
};
