sources:
  - name: Employees
    handler:
      mysql:
        host: localhost
        port: 3306
        user: root
        password: college
        database: employees
        tables: departments, titles
