sources:
  - name: Employees
    handler:
      mysql:
        host: localhost
        port: 33306
        user: root
        password: passwd
        database: employees

documents:
  - example-query.graphql
