sources:
  - name: Fake API
    handler:
      jsonSchema:
        baseUrl: https://not-existing-api.com/API
        operations:
          - type: Query
            field: users
            path: /users
            method: GET
            responseSchema: ./json-schemas/users.json
          - type: Query
            field: company
            path: /company/{args.id}
            method: GET
            responseSchema: ./json-schemas/company.json
    transforms:
      - mock:
          mocks:
            - apply: User.firstName
              faker: '{{name.firstName}}'
            - apply: User.lastName
              faker: '{{name.lastName}}'
            - apply: User.jobTitle
              faker: '{{name.jobTitle}}'
            - apply: Company.name
              faker: '{{company.companyName}}'
