sources:
  - name: OneIncTransactionsByType
    handler:
      jsonSchema:
        baseUrl: https://testapiprocessone.oneincsystems.com/api/
        operations:
          - type: Query
            field: transactions
            path: Transaction/GetTransactionsByType
            method: POST
            requestSample: ./json-samples/transactionsByTypeInput.json
            responseSample: ./json-samples/transactionsByType.json
            responseSchema: ./json-schemas/transactionsByType.json
