openapi: 3.1.0
info:
  title: Authors Example
  version: 1.0.0
paths:
  /authors:
    get:
      operationId: authors
      description: Returns a list of authors
      responses:
        '200':
          description: A list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
  /authors/{id}:
    get:
      operationId: author
      description: Returns a single author
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: The author was not found
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email

