sources:
  - name: TripPin
    handler:
      odata:
        endpoint: https://services.odata.org/TripPinRESTierService/(S(qzsyox3345c15qeq305pblvw))/
        batch: multipart
        expandNavProps: true

documents:
  - example-query.graphql
