sources:
  - name: Microsoft Graph
    handler:
      odata:
        baseUrl: https://graph.microsoft.com/${GRAPH_VERSION:v1.0}
        batch: json
        operationHeaders:
          Authorization: Bearer {context.cookies.accessToken}

serve:
  port: 4000
  exampleQuery: example-queries/**/*.graphql
  staticFiles: public

introspectionCache: ./introspection-cache-${GRAPH_VERSION:v1.0}.json
