sources:
  - name: Microsoft Graph
    handler:
      odata:
        endpoint: https://graph.microsoft.com/{env.GRAPH_VERSION}
        batch: json
        operationHeaders:
          Authorization: Bearer {context.cookies.accessToken}

documents:
  - example-queries/**/*.graphql

serve:
  port: 4000
  staticFiles: public
  playground: true
