sources:
  - name: OpenBrewery
    handler:
      jsonSchema:
        baseUrl: https://api.openbrewerydb.org
        operations:
          - type: Query
            field: breweries
            path: breweries
            method: GET
            requestSample: ./json-samples/breweriesInput.json
            responseSample: ./json-samples/breweries.json
