sources:
  - name: Rfam
    handler:
      mysql:
        host: mysql-rfam-public.ebi.ac.uk
        port: 4497
        user: rfamro
        database: Rfam

serve:
  exampleQuery: example-query.graphql
