sources:
  - name: Neo4j
    handler:
      neo4j:
        endpoint: neo4j+s://demo.neo4jlabs.com
        username: recommendations
        password: recommendations
        database: recommendations

documents:
  - ./example-query.graphql
