sources:
  - name: Neo4j
    handler:
      neo4j:
        url: bolt://localhost
        username: neo4j
        password: test
        cacheIntrospection:
          ttl: 3600

cache:
  file:
    path: ./mesh-cache.json
