sources:
  - name: Neo4j
    handler:
      neo4j:
        endpoint: bolt://demo.neo4jlabs.com:7687
        username: movies
        password: movies
        database: movies

documents:
  - ./example-query.graphql
