import { withGuildDocs } from 'guild-docs/next.config';
import { applyUnderscoreRedirects } from 'guild-docs/underscore-redirects';

export default withGuildDocs({
  basePath: process.env.NEXT_BASE_PATH && process.env.NEXT_BASE_PATH !== '' ? process.env.NEXT_BASE_PATH : undefined,
  experimental: {},
  images: {
    unoptimized: true, // doesn't work with `next export`
    allowFutureImage: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  webpack(config, meta) {
    applyUnderscoreRedirects(config, meta);

    return config;
  },
  redirects: () =>
    Object.entries({
      '/docs/introduction': '/docs',
      '/docs/getting-started': '/docs',
      '/docs/getting-started/introduction': '/docs',
      '/docs/getting-started/basic-example': '/docs',
      '/docs/handlers': '/docs/handlers/handlers-introduction',
      '/docs/handlers/available-handlers': '/docs/handlers/handlers-introduction',
      '/docs/api/modules/runtime_src': '/docs/getting-started/your-first-mesh-gateway',
      '/docs/recipes': '/docs',
      '/docs/api': '/docs',
      '/docs/modules': '/docs',
      '/docs/api/modules': '/docs',
      '/docs/api/interfaces/types_src.YamlConfig.FilterHelperArgsOpts': '/docs',
      '/docs/api/classes/apollo_link_src.MeshApolloLink': '/docs',
      '/docs/api/classes': '/docs',
      '/docs/api/modules/json_machete_src': '/docs/handlers/json-schema',
      '/docs/recipes/as-gateway': '/docs/getting-started/your-first-mesh-gateway',
      '/docs/guides/combine-many-sources': '/docs/getting-started/combine-multiple-sources',
      '/docs/api/modules/urql_src': '/docs',
      '/docs/guides': '/docs',
      '/docs/recipes/multiple-apis': '/docs/getting-started/combine-multiple-sources',
      '/docs/recipes/as-sdk': '/docs/guides/mesh-sdk',
      '/docs/migration/openapi-0': '/docs/migration/openapi-0.31-0.32',
      '/docs/recipes/build-mesh-artifacts': '/docs/guides/mesh-sdk',
      '/docs/api/interfaces/types_src.YamlConfig.RateLimitPluginConfig': '/docs/getting-started/customize-mesh-server',
      '/docs/api/classes/utils_src.DefaultLogger': '/docs/getting-started/customize-mesh-server',
      '/docs/api/classes/handlers_mysql_src.MySQLHandler': '/docs/handlers/mysql',
      '/docs/api/interfaces/types_src.YamlConfig.CorsConfig': '/docs/getting-started/customize-mesh-server',
      '/docs/api/modules/plugins_prometheus_src': '/docs/getting-started/customize-mesh-server',
      '/docs/api/interfaces/types_src.YamlConfig.ServeConfig': '/docs/getting-started/customize-mesh-server',
      '/docs/api/interfaces/types_src.YamlConfig.SortHelperArgsOpts': '/docs/getting-started/customize-mesh-server',
      '/docs/api/modules/handlers_grpc_src': '/docs/handlers/grpc',
      '/docs/api/modules/loaders_openapi_src': '/docs/handlers/openapi',
      '/docs/api/modules/jit_executor_src': '/docs/getting-started/customize-mesh-server',
      '/docs/api/modules/handlers_raml_src': '/docs/handlers/openapi',
      '/docs/api/modules/loaders_raml_src': '/docs/handlers/openapi',
      '/docs/api/interfaces/types_src.YamlConfig.OpenapiHandler': '/docs/handlers/openapi',
      '/docs/api/interfaces/types_src.YamlConfig.QueryStringOptions1': '/docs',
      '/docs/api/modules/handlers_mongoose_src': '/docs/handlers/mongoose',
      '/docs/api/interfaces/types_src.YamlConfig.ComposeWithMongooseFieldsOpts': '/docs/handlers/mongoose',
      '/docs/api/interfaces/runtime_src.MeshInstance': '/docs/guides/mesh-sdk',
      '/docs/api/modules/utils_src': '/docs/getting-started/customize-mesh-server',
      '/docs/api/interfaces/types_src.YamlConfig.Plugin': '/docs/getting-started/customize-mesh-server',
      '/docs/api/interfaces/types_src.YamlConfig.Transform': '/docs/getting-started/customize-mesh-server',
      '/docs/api/interfaces/types_src.MeshTransform': '/docs/getting-started/customize-mesh-server',
      '/docs/api/modules/transforms_rename_src': '/docs/transforms/rename',
      '/docs/api/modules/config': '/docs',
      '/docs/api/modules/config_src': '/docs',
      '/docs/api/modules/transforms_prefix_src': '/docs',
      '/docs/api/interfaces/types_src.YamlConfig.PrefixTransformConfig': '/docs',
      '/docs/api/interfaces': '/docs',
      '/docs/api/classes/cache_file_src.FileCache': '/docs',
      '/docs/recipes/federation': '/docs',
      '/docs/api/modules/plugins_rate_limit_src': '/docs',
      '/docs/api/modules/transforms_hoist_field_src': '/docs',
      '/docs/guides/performances-best-practices': '/docs',
      '/docs/api/interfaces/types_src.YamlConfig.ComposeWithMongooseResolverOpts': '/docs',
      '/docs/api/interfaces/types_src.YamlConfig.SoapHandler': '/docs',
      '/docs/api/modules/transforms_prune_src': '/docs',
      '/docs/api/modules/merger-bare': '/docs',
      '/docs/api/interfaces/json_machete_src.JSONSchemaObject': '/docs',
      '/docs/api/classes/transforms_encapsulate_src.EncapsulateTransform': '/docs',
      '/docs/api/classes/transforms_encapsulate_src': '/docs',
      '/docs/api/interfaces/types_src.YamlConfig.CacheEffectingOperationConfig': '/docs',
      '/docs/getting-started/combine-many-sources': '/docs',
      '/docs/recipes/typescript': '/docs',
      '/docs/api/modules/plugins_mock_src': '/docs',
      '/docs/transforms': '/docs',
      '/docs/api/modules/plugins_webhook_src': '/docs',
      '/docs/cache/inmemory-lru': '/docs',
      '/docs/cache': '/docs',
      '/docs/recipes/subscriptions-webhooks': '/docs/guides/subscriptions-webhooks',
      '/docs/getting-started/mesh-transforms': '/docs/transforms/transforms-introduction',
      '/docs/getting-started/multiple-apis': '/docs/getting-started/combine-multiple-sources',
      '/docs/api/interfaces/types_src.MeshPubSub': '/docs/guides/subscriptions-webhooks',
      '/docs/api/interfaces/loaders_json_schema_src.JSONSchemaLoaderBundleToGraphQLSchemaOptions':
        '/docs/handlers/json-schema',
      '/docs/subscriptions-webhooks': '/docs/guides/subscriptions-webhooks',
      '/docs/api/interfaces/loaders_json_schema_src.BundleJSONSchemasOptions':
        '/docs/handlers/json-schema',
      '/docs/api/modules/transforms_snapshot_src': '/docs/transforms/snapshot',
      '/docs/api/modules/string_interpolation_src': '/docs/transforms/transforms-introduction',
      '/docs/api/interfaces/types_src.YamlConfig.HTTPSConfig': '/docs/handlers/json-schema',
      '/docs/recipes/live-queries': '/docs/guides/live-queries',
      '/docs/handlers/new-openapi': '/docs/handlers/openapi',
      '/docs/api/modules/handlers_mysql_src': '/docs/handlers/tuql',
      '/docs/api/interfaces/loaders_json_schema_src.TypeComposers': '/docs/handlers/json-schema',
      '/docs/api/interfaces/types_src.YamlConfig.GraphQLHandlerMultipleHTTPConfiguration': '/docs/handlers/json-schema',
      '/docs/api/interfaces/store_src.FsStoreStorageAdapterOptions': '/docs/guides/file-uploads',
      '/docs/api/interfaces/types_src.YamlConfig.LiveQueryPolling': '/docs/guides/live-queries',
      '/docs/api/classes/store_src.MeshStore': '/docs',
      '/docs/api/interfaces/types_src.YamlConfig.ResolversCompositionTransformObject': '/docs/handlers/json-schema',
      '/docs/api/modules/handlers_postgraphile_src': '/docs/handlers/postgraphile',
      '/docs/api/modules/handlers_openapi_src': '/docs/handlers/openapi',
      '/docs/api/cli': '/docs/cli-commands',
      '/docs/api/interfaces/types_src.YamlConfig.ComputedAnnotation': '/docs',
    }).map(([from, to]) => ({
      source: from,
      destination: to,
      permanent: true,
    })),
});
