module.exports = {
  sidebar: {
    'Getting Started': [
      'getting-started/introduction',
      'getting-started/installation',
      'getting-started/basic-example',
    ],
    Recipes: [
      'recipes/multiple-apis',
      'recipes/build-mesh-artifacts',
      'recipes/typescript',
      'recipes/as-sdk',
      'recipes/as-gateway',
      'recipes/custom-server',
      'recipes/subscriptions-webhooks',
      'recipes/live-queries',
    ],
    'Source Handlers': [
      'handlers/handlers-introduction',
      'handlers/graphql',
      'handlers/openapi',
      'handlers/grpc',
      'handlers/json-schema',
      'handlers/postgraphile',
      'handlers/soap',
      'handlers/mongoose',
      'handlers/odata',
      'handlers/thrift',
      'handlers/tuql',
      'handlers/mysql',
      'handlers/neo4j',
    ],
    Transforms: [
      'transforms/transforms-introduction',
      'transforms/rename',
      'transforms/prefix',
      'transforms/encapsulate',
      'transforms/cache',
      'transforms/snapshot',
      'transforms/mock',
      'transforms/resolvers-composition',
      'transforms/filter-schema',
      'transforms/replace-field',
      'transforms/naming-convention',
      'transforms/type-merging',
      'transforms/federation',
      'transforms/extend',
    ],
    Cache: ['cache/inmemory-lru', 'cache/cache-file', 'cache/localforage', 'cache/cache-redis'],
    'API Reference': require('./api-sidebar.json'),
    // 'Extend Your Mesh': ['extend/custom-handler', 'extend/custom-transform']
  },
};
