sources:
  - name: PetStore
    handler:
      openapi:
        # source: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml
        source: petstore.yaml
  - name: PetStoreExtended
    handler:
      openapi:
        # source: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml
        source: petstore-expanded.yaml
