sources:
  - name: Covid
    handler:
      graphql:
        endpoint: https://covid-19-two-rust.vercel.app/api/graphql
  - name: WorldPop
    handler:
      jsonSchema:
        baseUrl: https://datasource.kapsarc.org/api/records/1.0/search
        operations:
          - type: Query
            field: population
            path: /?dataset=world-population&q={args.country}&rows=1&sort=year&facet=year&facet=country_name
            method: GET
            responseSchema: ./src/json-schemas/worldPop.json
            argTypeMap:
              country: String

additionalTypeDefs: |
  extend type Case {
    population: ApiPopulation
  }
  extend type Query {
    stat(country: String!): Stat
  }
  type Stat {
    confirmedRatio: Float
    deathRatio: Float
    case: Case
    population: ApiPopulation
  }
additionalResolvers:
  - targetTypeName: Case
    targetFieldName: population
    requiredSelectionSet: |
      {
        countryRegion
      }
    sourceName: WorldPop
    sourceTypeName: Query
    sourceFieldName: population
    sourceArgs:
      country: '{root.countryRegion}'
  - ./src/query-additional-resolvers.js

documents:
  - example-queries/*.graphql
