sources:
  - name: Calculator
    handler:
      thrift:
        idl: ./src/thrift/calculator.thrift
        hostName: localhost
        port: 9876
        path: /thrift
        serviceName: calculator-service

documents:
  - ./example-query.graphql
