name: Check Configuration
on:
  pull_request:
    branches:
      - master
jobs:
  check-configuration:
    name: Check Configuration Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Detect Changes
        if: github.repository == 'urigo/graphql-mesh'
        uses: kamilkisiela/graphql-inspector@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:schema.graphql'
