name: dependencies
on:
  pull_request:
    branches:
      - master


jobs:
  changesets-dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@pipelines
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
