name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@shared-setup
    with:
      script: 'yarn ci:lint'
      annotations: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
