name: release

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  YARN_ENABLE_HARDENED_MODE: 0
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  dependencies:
    if:
      ${{ github.event.pull_request.title != 'Upcoming Release Changes' && github.base_ref ==
      'master' }}
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yml@v1
    with:
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  alpha:
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@v1
    with:
      node-version-file: .node-version
      npmTag: alpha
      buildScript: build
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  stable:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    if: github.ref == 'refs/heads/master'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@v1
    with:
      releaseScript: release
      versionScript: 'changeset-version'
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
