sources:
  - name: ExampleAPI
    handler:
      openapi:
        endpoint: http://localhost:4001
        source: http://localhost:4001/openapi.json
        ignoreErrorResponses: true

additionalTypeDefs: |
  extend type Query {
    user(id: Float!): User
  }

additionalResolvers:
  - ./additional-resolvers.ts

serve:
  browser: false

documents:
  - ./example-query.graphql
